### ISSUE TITLE
How to execute widgets from inside functions?

### ISSUE THREAD

**Issue by OmeGak** [zsh-users/zsh-autosuggestions#183]
I'm trying to execute `autosuggest-clear` and `autosuggest-accept` from inside a function. This is my most basic case:

``` bash
foo() {
  # ... other code
  zle autosuggest-clear
}
zle -N foo
bindkey '^K' foo
```

`foo` gets executed on `Ctrl + K`, but `zle autosuggest-clear` does nothing. Am I missing something?

**Comment by ericfreese** [comment]
Ah, yeah this is kind of confusing behavior, but I think it has to do with the fact that any un-mapped widget (those not included in any of [these configured lists](https://github.com/zsh-users/zsh-autosuggestions/blob/v0.3.2/src/config.zsh#L16-L49)) currently triggers the fetching and display of a new suggestion after running.


From the [readme](https://github.com/zsh-users/zsh-autosuggestions#widget-mapping):

> Widgets not in any of these lists will update the suggestion when invoked.

So your `foo` widget is wrapped by z-asug, and when invoked with `^K`: (1) clears the suggestion via `zle autosuggest-clear`, and then (2) the modification behavior is triggered, which fetches a new suggestion. That new suggestion will likely be the same as the last, so it appears that the suggestion was not cleared at all.

Instead of calling `zle autosuggest-clear` from your widget, I'd suggest adding the `foo` widget to the list of widgets that clear the autosuggestion:

```shell
% function foo() { ... }
% zle -N foo
% bindkey '^K' foo
% ZSH_AUTOSUGGEST_CLEAR_WIDGETS +=(foo)
```

A potential fix to this problem may be to change the logic of the `modify` widget to only fetch and display a new suggestion if the wrapped widget actually changes the actual `$BUFFER` content.

**Comment by ericfreese** [comment]
The [fixes/only_fetch_if_buffer_changed](https://github.com/zsh-users/zsh-autosuggestions/tree/fixes/only_fetch_if_buffer_changed) branch implements the fix described at the bottom of my last comment. Try it out and let me know what you think.

**Comment by OmeGak** [comment]
Seems to be working for me. Thanks!
