### ISSUE TITLE
Showing only history

### ISSUE THREAD

**Issue by srajasimman** [zsh-users/zsh-autosuggestions#196]
I followed the same README.md to install in my existing oh my zsh custome folder.
but its not working. only shows suggestions from existing history.

**Comment by sheparddw** [comment]
Are you saying:
1. It only shows suggestions for your current session history, not persistent history
or
2. It should suggest more than only history?

If 1, you can persist history via the following in your .zshrc:
```
SAVEHIST=100 # Save history to 100 commands.
HISTFILE=~/.zsh_history # Store history to persist across sessions.
```

**Comment by srajasimman** [comment]
No,
1. It only shows suggestions from my current and persistent history. not for new commands and command line arguments/file names.  
2. suggestions only in same color not in faded color.

**Comment by sheparddw** [comment]
Oh, I see. It only suggests from my history as well.
I expect commands/paths to be suggested as well.
@tarruda, or anyone else, is this a feature request or improper configuration that we are experiencing?

@srajasimman, I do not have the issue with the color not being faded. Have you tried a different zsh or terminal theme?

**Comment by tarruda** [comment]
> @tarruda, or anyone else, is this a feature request or improper configuration that we are experiencing?

AFAIK, only history is used for suggestions.

In the initial versions, this project used asynchronous suggestions from a server component that ran in the background(started on user login) that used data from all user completion functions, but I was unable to get it working properly due to a limitation zsh had at the time.

It might be possible to get it working in newer versions of zsh, but I never got the time to do it. If you want to give it a shot, I suggest to search in the initial commits in the repository for a proof-of-concept implementation.

**Comment by ericfreese** [comment]
Yep, the plugin currently only offers suggestions based on your history. #111 asks for the ability to offer suggestions for new commands and arguments. Going to go ahead and close this as a duplicate of that.
