### ISSUE TITLE
Breaks multi-line commands

### ISSUE THREAD

**Issue by braykov** [zsh-users/zsh-autosuggestions#209]
If I type the beginning of a previous multi-line command, such as while... or for..., when I hit END key, the whole command comes on a single line, concatenated with "\n\", exactly as it is kept in "history".
However this command is invalid and cannot be invoked/repeated.

I get:
`while true\ndo\nls\nsleep 300\npwd\nsleep 300\ndone`

I expected:
```
while true
do
ls
sleep 300
pwd
sleep 300
done
```

**Comment by ericfreese** [comment]
Looks like this was introduced in `v0.3.3`. `v0.3.2` does not seem to have this issue.

**Comment by ericfreese** [comment]
@modk it looks like multi-line history entries output via `fc` have their newlines swapped out for "\n", making it impossible to tell which we should use when displaying the suggestion.

```shell
% abc="
dquote> "
% abc="\n"
% fc -ln
abc="\n"
abc="\n"
```

Any thoughts on how to get around this? It occurred to me we could use `fc` to get the history entry number and then index into `$history` to get the correct suggestion to show. Something like:

```shell
$history[$(fc -lrm "$prefix*" 1 2>/dev/null | head -n 1 | cut -c 1-5 | tr -d ' ')]
```

But that will only work for history entries less than 100,000 because [`fc` seems to only show a maximum of 5 digits](https://github.com/zsh-users/zsh/blob/zsh-5.3/Src/builtin.c#L1798).

I think I'm going to go ahead and switch it back to using `$history` subscripting since [async should be coming along shortly](https://github.com/zsh-users/zsh-autosuggestions/pull/180), which will make it much less bothersome when fetching a suggestion takes a long time.

**Comment by ericfreese** [comment]
This should now be fixed on `develop`. Please check out that branch and let me know if it is still an issue.
