### ISSUE TITLE
autosuggest-accept triggers bell when binded to non-standard hotkey

### ISSUE THREAD

**Issue by popstas** [zsh-users/zsh-autosuggestions#228]
Example:
```
bindkey '^u' autosuggest-accept
bindkey '`' autosuggest-accept
```
When I press Ctrl+U or ` terminal triggers bell. When I press &rarr; or End, autosuggest accepted without bell.

Bell triggers in any case, when autosuggest present or absent.

**Comment by okdana** [comment]
This happens because `_zsh_autosuggest_invoke_original_widget()` returns `1` when provided no 'original widget' (which it won't be in this case), and the `_zsh_autosuggest_widget_*()` functions pass this status on. Per the ZLE widget documentation:

>A non-zero return status causes the shell to beep when the widget exits, unless the BEEP options was unset or the widget was called via the zle command.

I'm not super familiar with the code base yet but i don't see any reason why `_zsh_autosuggest_invoke_original_widget()` needs to return `1` here — it's not an error condition and it doesn't seem to provide any other useful information to the caller. I've only tested briefly but i haven't seen any issues so far with just having it always return `0` when there are no arguments.

**Comment by popstas** [comment]
@okdana, thank you! It works for me, will test it.

**Comment by ericfreese** [comment]
Should be fixed on `develop` branch now thanks to @okdana
