### ISSUE TITLE
Use Ctrl+Enter for executing current autosuggestion; Using 

### ISSUE THREAD

**Issue by moritzschaefer** [zsh-users/zsh-autosuggestions#255]
I have an issue regarding keybindings:
- How can I replace the Up-key with Ctrl+k such that I move to the next possible suggestion with vi-like bindings?
Unfortunately I didn't find any documentation on which keybinding I have to set to make this work.

- How can I use Ctrl+Enter to execute the currently shown suggestion? "^M" corresponds to Enter, I don't see a way to add the Ctrl control-sequence

Thanks for help

**Comment by mattsoutherden** [comment]
Regarding the second part, your terminal emulator probably does not distinguish between `Enter`, `Ctrl-Enter`, and `Shift-Enter`. You can check this by hitting `Ctrl-v Enter`, `Ctrl-v Ctrl-Enter`... They most likely all send `^M`.

One solution is to create a custom keycode. I've used iTerm to send the escape sequence `[[CE`, and then used the binding `bindkey '^[[[CE' autosuggest-execute`

In iTerm, this is done  under`Profile` -> `Keys`. Click the `+` to add a new mapping, enter the desired key sequence, and then choose `Send Escape Sequence`

**Comment by ericfreese** [comment]
> How can I replace the Up-key with Ctrl+k such that I move to the next possible suggestion with vi-like bindings?

This plugin doesn't support cycling through suggestions. To see what the up-key is bound to in your environment, type `bindkey '`, hit <kbd>ctrl</kbd>+<kbd>v</kbd> and the up arrow, then close the quote `'` and hit enter. On my machine this looks like this:

```
% bindkey '^[[A'
"^[[A" up-line-or-history
```

Meaning that the up key is bound to the `up-line-or-history` widget. In order to bind <kbd>ctrl</kbd>+<kbd>k</kbd> to `up-line-or-history`, run `bindkey '^K' up-line-or-history`. If you want that to take effect on every zsh session going forward, add it to your `.zshrc`.

> How can I use Ctrl+Enter to execute the currently shown suggestion? "^M" corresponds to Enter, I don't see a way to add the Ctrl control-sequence

In addition to @mattsoutherden's answer, check out a previous question here: https://github.com/zsh-users/zsh-autosuggestions/issues/154

**Comment by timfeirg** [comment]
this is what I have in my `.zshrc` and it works:

```sh
export ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
export ZSH_AUTOSUGGEST_USE_ASYNC=1
antigen bundle zsh-users/zsh-autosuggestions
bindkey '^[[[CE' autosuggest-execute
```

did you load the autosuggest plugin before the bindkey command? could you post your `.zshrc`? @bbuchalter

**Comment by mattsoutherden** [comment]
Sorry, not sure. I have not been able to replicate that behaviour, so I can't suggest what may be causing it.
