### ISSUE TITLE
ZSH_AUTOSUGGEST_USE_ASYNC causes pasting content repeat 

### ISSUE THREAD

**Issue by zyf0330** [zsh-users/zsh-autosuggestions#274]
If I open `ZSH_AUTOSUGGEST_USE_ASYNC` option, and paste `echo $ZSH_AUTOSUGGEST_USE_ASYNC` into terminal, I get 
```
echo $ZSH_AUTOSUGGEST_USE_ASYNC^@echo $ZSH_AUTOSUGGEST_USE_ASYNC^@echo $ZSH_AUTOSUGGEST_USE_ASYNC^@echo $ZSH_AUTOSUGGEST_USE_ASYNC^@echo $ZSH_AUTOSUGGEST_USE_ASYNC^@echo $ZSH_AUTOSUGGEST_USE_ASYNC^@echo $ZSH_AUTOSUGGEST_USE_ASYNC^@echo $ZSH_AUTOSUGGEST_USE_ASYNC^@echo $ZSH_AUTOSUGGEST_USE_ASYNC^@echo $ZSH_AUTOSUGGEST_USE_ASYNC^@echo $ZSH_AUTOSUGGEST_USE_ASYNC^@echo $ZSH_AUTOSUGGEST_USE_ASYNC^@echo $ZSH_AUTOSUGGEST_USE_ASYNC^@echo $ZSH_AUTOSUGGEST_USE_ASYNC^@echo $ZSH_AUTOSUGGEST_USE_ASYNC^@echo $ZSH_AUTOSUGGEST_USE_ASYNC^@echo $ZSH_AUTOSUGGEST_USE_ASYNC^@echo $ZSH_AUTOSUGGEST_USE_ASYNC^@echo $ZSH_AUTOSUGGEST_USE_ASYNC
```
Yes, it repeat pasting content so many multiple times as gray suggestions.

**Comment by ericfreese** [comment]
Interesting. Do you get this behavior without your custom config loaded? Try running `zsh -f` and sourcing the plugin manually `source zsh-autosuggestions.zsh; ZSH_AUTOSUGGEST_USE_ASYNC=true`

**Comment by zyf0330** [comment]
When `zsh -f` and `source ...`, it is ok.
This my plugins `plugins=(command-not-found zsh-autosuggestions zsh-syntax-highlighting zsh-history-substring-search)`, and I find that if I remove ` zsh-syntax-highlighting ` then it works normally.

**Comment by ericfreese** [comment]
> And actually I don't know async_mode's advantages. What is it?

Some people were having issues where, when they typed quickly, the terminal was lagging behind their typing because it was fetching a suggestion on every keystroke. Async mode puts that suggestion-fetching in the background so typing is not blocked by it.

**Comment by zyf0330** [comment]
I guess that is the reason and you confirm it. So how about first problem?

**Comment by ericfreese** [comment]
Not sure about the first problem. The first step to diagnose would be to strip down your zshrc until you determine which line or lines is causing the issue. Once we figure out exactly what's causing the issue, we can get a fix in place. I don't tend to personally prioritize the bugs that arise from compatibility between plugins, since it tends to take a relatively long time and I don't often use the mentioned plugins personally. So it would be helpful if you (or someone else with the problem) could dig in a bit and get some more details on exactly what's going on here.

**Comment by zyf0330** [comment]
After upgrading zsh, this problem disappeared.
