### ISSUE TITLE
bindkey with Ctrl+Space triggers a bell sound and doesn't overwrite the default shortcut

### ISSUE THREAD

**Issue by revolter** [zsh-users/zsh-autosuggestions#311]
Adding `bindkey '^ ' autosuggest-accept` in a `.zsh` file in the `$ZSH_CUSTOM` folder doesn't disable the default "right arrow" shortcut and it also causes a bell sound, while the default one doesn't.

**Comment by ericfreese** [comment]
Hi, adding a binding for autosuggest-accept is not intended to remove the behavior of forward-char. To remove that functionality you'll need to remove forward-char from the list of widgets that accept the suggestion. See the config section of the readme: https://github.com/zsh-users/zsh-autosuggestions/blob/master/README.md#widget-mapping

The bell sound on autosuggest-accept has been fixed on develop branch (see #304). You may wish to use that branch instead of master.

**Comment by revolter** [comment]
The first problem was solved, thank you!

But the second one didn't. I have

> exa v0.9.0-pre (0eb7966 built on 2018-02-12)

and restarted iTerm but it still triggers a bell sound when I press Ctrl+Space.

**Comment by ericfreese** [comment]
Hmm I'm not sure what software that version (0.9.0-pre) is coming from but the highest version of this plugin is 0.4.2. And I'm referring to the develop branch of this repo: https://github.com/zsh-users/zsh-autosuggestions/tree/develop
