### ISSUE TITLE
Feature request: Suggest most frequently used command

### ISSUE THREAD

**Issue by fdw** [zsh-users/zsh-autosuggestions#317]
I think it might be neat to suggest the most often used command instead of the most recently used.

For example, if I have this history (with duplicates allowed, naturally):
```
echo 1
echo 1
echo 2
```
the suggestion should be
```
echo 1
```
as that is more often used.

Do you think this would be a good addition?

**Comment by ericfreese** [comment]
I can't guarantee I'll merge it, but you should be able to implement this at least for yourself with a custom suggestion strategy. See https://github.com/zsh-users/zsh-autosuggestions/pull/315 for an example of how to achieve that.

**Comment by ericfreese** [comment]
I recently came across this project that stores your zsh history in a SQLite database. With a custom suggestion strategy making the right query, this behavior can be implemented.

https://github.com/larkery/zsh-histdb/blob/master/README.org#integration-with-zsh-autosuggestions

Going to go ahead and close this issue since the requested behavior is possible with another tool and a bit of config.
