### ISSUE TITLE
Autosuggestions needs re-learn history in the new terminal

### ISSUE THREAD

**Issue by claford-v-lawrence** [zsh-users/zsh-autosuggestions#405]
After closing a terminal and open another, it will work only if I have type in the same command. For example, if I type pwd in the first terminal, it will autosuggest after typing p. However, if I reopen a terminal, it will not hint anything until I have executed the pwd command again.

**Comment by ericfreese** [comment]
This is because zsh-autosuggestions by default is powered by your shell history and zsh by default doesn't persist history between sessions. You'll need to configure zsh to persist shell history if you want zsh-autosuggestions  to make suggestions based on commands run under previous sessions.

This stack overflow answer may be helpful: https://unix.stackexchange.com/a/389883/156673
