### ISSUE TITLE
failed to load module: zsh/system

### ISSUE THREAD

**Issue by davxiao** [zsh-users/zsh-autosuggestions#441]
When loading it fails with this message: "[~] source ~/.zshrc
`/volume1/homes/david/.oh-my-zsh/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh:729: failed to load module: zsh/system"`

It is installed on NAS Synology with community zsh package and oh-my-zsh. 
~/.zshrc has the following plugins loaded: 
`plugins=(git docker zsh-autosuggestions history-substring-search)`

**Comment by ericfreese** [comment]
We probably could also degrade a bit when zsh/system isn't available. It's only used when async mode is enabled for the suggestion-fetching background process to send it's process id to the main process so that, as suggestions are quickly fetched, the main process can kill background processes as they're no longer needed so they don't hog resources.

Seems there could be two potential fixes:

1) Only require zsh/system if/when async mode is enabled. Folks without it could still use the sync mode.
2) For people with zsh/system missing, don't try to kill any background processes, just let them finish. Could use a bit more resources, but should work fine I think.

I think I lean toward option 2

**Comment by ericfreese** [comment]
@davxiao Please try `features/without-system-module` branch (#447) and confirm it fixes the issue for you.

**Comment by davxiao** [comment]
Hi thanks for all the help. 
I can confirm the issue I was having was due to the zsh distribution I was using does not have built-in modules. I was able to fix the issue by just installing a zsh with modules. 
Closing this issue here.

**Comment by ericfreese** [comment]
Ok :+1: went ahead and merged that PR anyway so in the future people shouldn't have issues if they happen to be missing zsh/system
