### ISSUE TITLE
Install script fails on raspbian 8 (jessie)

### ISSUE THREAD

**Issue by mhsattarian** [zsh-users/zsh-autosuggestions#484]
### Describe the bug

When installing `zsh-autosuggestions` for `oh-my-zsh` on **raspberry pi 3B raspbian (jessie)**, it fails to understand the `{ZSHCUSTOM:-` part in the install script, and so fails to correctly install the plugin.

### To Reproduce

On raspberry (jessie) do as follows:
1. Install `zsh-autosuggestions` plugin for `oh-my-zsh` using command bellow:

```shell
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
```

2. add `zsh-autosuggestions` to plugins section in `~/.zshrc` and do `source ~/.zshrc`.

3. restart the terminal and a warning saying `[oh-my-zsh] plugin 'zsh-autosuggestions' not found` is displayed.

4. check the `~/.oh-my-zsh/custom/plugins` and `~/.oh-my-zsh/plugins` directories. 

### Expected behavior

It should have created `zsh-autosuggestions` directory in `~/.oh-my-zsh/custom/plugins` instead of creatign a wrong directory called `{ZSHCUSTOM:-` in `~/.oh-my-zsh/plugins`.

### Screenshots

![Screenshot_2](https://user-images.githubusercontent.com/29674767/70334452-b6219980-185a-11ea-9a63-e39170b3ce05.png)

### Desktop
 - OS + distribution: Raspbian GNU/Linux 8 (jessie)
 - Zsh version: 5.0.7
 - Plugin version: d43c309

**Comment by ericfreese** [comment]
Interesting. I would have expected the `${name:-word}` [parameter expansion](http://zsh.sourceforge.net/Doc/Release/Expansion.html#Parameter-Expansion) to work on all platforms. If it is indeed not working right on your distro (I would confirm this with `zsh -dfc "echo ${FOO:-foo}"`), I think that would be an upstream bug, not something to be fixed in this plugin.
