### ISSUE TITLE
Custom widgets not working when widget name starts with `autosuggest-`

### ISSUE THREAD

**Issue by Dzordzu** [zsh-users/zsh-autosuggestions#496]
Hi. I've tried to define a custom wiget for my zsh. Basically - it's not working, autocompletion does not work. Config is rather straightforward

```zsh
function autosuggest-partial-accept {
   CURSOR+=1
}
zle -N autosuggest-partial-accept
bindkey -v '^g' autosuggest-partial-accept
```

```zsh
ZSH_AUTOSUGGEST_PARTIAL_ACCEPT_WIDGETS=(
      autosuggest-partial-accept
)
```

What am I supposed to do, in order to get it to work? Thanks in advance

It's not actually a bug report, or a feature request. It's more like a requst for the help

**Comment by ericfreese** [comment]
To get your code working now, you need to prefix your widget with something other than `autosuggest-`. That prefix is currently [ignored when we wrap existing widgets with autosuggestion functionality](https://github.com/zsh-users/zsh-autosuggestions/blob/ae315ded4dba10685dbbafbfa2ff3c1aefeb490d/src/bind.zsh#L72-L72) so that we don't wrap our own widgets.

However, there's not really a good reason for this behavior. We should just be able to ignore the specific existing widgets (`autosuggest-fetch`, `autosuggest-suggest`, etc.) instead of all matching `autosuggest-*`.

Let's leave this open as a bug and I'll fix it at some point.
