### ISSUE TITLE
shell under Cygwin with ZSH_AUTOSUGGEST_STRATEGY=(completion) completly non responsive

### ISSUE THREAD

**Issue by avielsh** [zsh-users/zsh-autosuggestions#497]
### Describe the bug
Hi
I've noticed that using the completion feature of zsh-autosuggestions under Cygwin, makes the prompt completly unresponsive. 
I'm aware of the slowness of cygwin's fork(), and using the history strategy, there's a small lag when typing , but after adding the completion option, the prompt will stop responding to any character typed.
Only solution I've found is to close the current shell and open a new one.

### To Reproduce
```sh
% zsh -df
% source path/to/zsh-autosuggestions.zsh
% ZSH_AUTOSUGGEST_STRATEGY=(completion)
```

### Expected behavior
Typing characters/commands on the prompt, should work normally (little lag is acceptable)

### Desktop
 - OS + distribution: Windows 7 + Cygwin 3.1.2 (Tried both 32bit and 64bit)
 - Zsh version: 5.5.1
 - Plugin version: 0.63

**Comment by avielsh** [comment]
Enabling  ZSH_AUTOSUGGEST_USE_ASYNC=1 makes the prompt responsive again..Still a lag but at least it's working…
I'm wondering if this setting affects something/should zsh-autosuggestions should work out of the box w/o this setting ?

**Comment by ericfreese** [comment]
Hey @avielsh, glad you were able to get things working.

I'm planning to switch the default from sync to async in an upcoming release. Thing is that async mode has a kind of annoying [bug in zsh versions less than 5.0.8](https://github.com/zsh-users/zsh-autosuggestions/issues/364#issuecomment-481423231), so we may need to keep sync mode around for some users since we support back to 4.3.11. I may do some smart version detection stuff and either enable async or disable it, or maybe just make it a config option to opt out. Not sure yet, but anyway... should be coming soon by default for most users.

A related issue: https://github.com/zsh-users/zsh-autosuggestions/issues/485

**Comment by avielsh** [comment]
Thanks @ericfreese,
The async option really speeds up things up, also on my Mac setup. 
I have missed it while skimming through the docs, but putting it on by default with version checking is important IMO, especially in situations like in Cygwin, which makes the shell completely unusable w/o it.

**Comment by ericfreese** [comment]
I’ve created an issue to track making it enabled by default: https://github.com/zsh-users/zsh-autosuggestions/issues/498
