### ISSUE TITLE
How to set ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE ?

### ISSUE THREAD

**Issue by alexzhaohong** [zsh-users/zsh-autosuggestions#523]
I wasn't able to find ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE in the Global Configuration Variables section. [config.zsh](https://github.com/zsh-users/zsh-autosuggestions/blob/master/src/config.zsh)

Do I have to modify zsh-autosuggestions.zsh right on line 350? I don't see where ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE is declared.

**Comment by mindyourlifeguide** [comment]
@alexzhaohong maybe you mean:
`ZSH_HIGHLIGHT_MAXLENGTH = 300`

**Comment by alexzhaohong** [comment]
Hmmm looking into it that seems to do something different. I'm trying to do the suggested change in the Configuration readme as shown here: 

[Disabling suggestion for large buffers
](https://github.com/zsh-users/zsh-autosuggestions#disabling-suggestion-for-large-buffers) 

> Set ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE to an integer value to disable autosuggestion for large buffers. The default is unset, which means that autosuggestion will be tried for any buffer size. Recommended value is 20. This can be useful when pasting large amount of text in the terminal, to avoid triggering autosuggestion for strings that are too long.

**Comment by ericfreese** [comment]
Hey @alexzhaohong, you’re not seeing it in the source because it’s not set by default. You can set it yourself by putting a line in your .zshrc file something like

`ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20`

In general you shouldn’t modify the source, but should override the values of the variables you want to configure in your .zshrc file.

**Comment by alexzhaohong** [comment]
Perfect! Thank you
