### ISSUE TITLE
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE not being used

### ISSUE THREAD

**Issue by rwmitchell** [zsh-users/zsh-autosuggestions#626]
### Describe the bug
I have a short terminal window.    Entering commands get interrupted with "do you wish to all all N possibilities".

### To Reproduce

Create a short (6 rows) terminal window

type:
``` 
     export ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=2
     alias[SPACE]
```

zsh prompts with:
```zsh: do you wish to see all 194 possibilities (23 lines)?```

### Expected behavior

Ideally I'd like to never see that prompt.  If the screen size allows the information to be displayed, just display it.  If it doesn't, indicate there are more options that can be displayed, but do not eat any input characters as that ruins the flow of what is b being typed.

An ideal solution would then allow a special keystroke to display all possibilities.

**Comment by ericfreese** [comment]
I think you might be confusing this plugin with the standard tab completion that zsh offers. This plugin doesn't control whether you do or don't see results when pressing tab or otherwise activating the zsh completion features.

You'll want to look at documentation for zsh completion rather than this plugin. You might like the behavior you get by setting `LISTPROMPT=''`. See https://zsh.sourceforge.io/Doc/Release/Zsh-Modules.html#Scrolling-in-completion-listings

**Comment by rwmitchell** [comment]
Maybe and likely I am confused.

Before installing this plugin, I had to use [TAB] to generate a list of completions.  Now, I am offered completions after every letter I type.  Normally this is an ok thing, up until I start getting prompted to see all possibilities and keystrokes get eaten.

Is that not this plugin that changed the behavior?
